config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :products, only: %i(show index)
  resources :carts, only: %i(index)
  resources :orders, only: %i(show create)
  resources :payments, only: %i(new create)
  post '/payments/cancel', to: 'payments#cancel'
  post '/payments/provider_notify', to: 'payments#provider_notify'
  root to: 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
  ##
# order model
class Order < ApplicationRecord
  # order allowed statuses
  STATUSES = %w(paid cancelled reserved shipped)
  PAID_STATUS = 'paid'
  RESERVED_STATUS = 'reserved'


  validates :amount, :status, :token, presence: true
  validates :amount, numericality: true

  has_many :products_orders, class_name: 'ProductOrder', inverse_of: :order
  has_many :products, through: :products_orders, inverse_of: :orders
  has_many :payments, inverse_of: :order

  accepts_nested_attributes_for :products_orders

  before_validation :set_status, :set_token, on: :create

  # sprawdza status wszystkich płatności danego zamówienia i zwraca jeden wspólny status
  #
  # jeśli co najmniej jedna płatność jest zakończona, wtedy zwraca statuc completed
  #
  # jeśli żadna płatność nie jest zakończona i co najmniej jedna oczekująca, wtedy zwraca status pending
  #
  # jeśli żadna płatność nie jest zakończona lub oczekująca i co najmniej jedna jest anulowana, wtedy zwraca status cancelled
  #
  # jeśli żadna płatność nie jest zakończona lub oczekująca lub anulowana wtedy zwraca status not started
  def payment_status
    return Payment::COMPLETED_STATUS if Payment.find_by(order_id: id, status: Payment::COMPLETED_STATUS)
    return Payment::PENDING_STATUS if Payment.find_by(order_id: id, status: Payment::PENDING_STATUS)
    return Payment::CANCELLED_STATUS if Payment.find_by(order_id: id, status: Payment::CANCELLED_STATUS)

    'not started'
  end

  private

  # po stworzeniu zamówienia ustala status jako reserved
  #
  # oznacza, że klient zamówił produkty, ale jeszcze nie dokonał płatności
  def set_status
    self.status = RESERVED_STATUS
  end

  # generuje nowy unikalny token który będzie jednoznacznie identyfikował zamówienie
  def set_token
    random_token = SecureRandom.alphanumeric(32)
    while Order.find_by(token: random_token).present? do
      random_token = SecureRandom.alphanumeric(32)
    end
    self.token = random_token
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show]

  # GET /orders/fhe6g32238fdkd839th587
  def show
  end

  # POST /orders
  #
  # tworzy zamówenie
  # 
  # redukuje liczbę produktów o zamówione produkty
  #
  # resetuje koszyk
  def create
    products = Product.where(id: order_params.keys)
    total_amount = 0

    products_orders = order_params.to_unsafe_h.map do |product_id, quantity|
      product = products.find { |p| p.id.to_s == product_id }
      amount = product.price * quantity.to_i
      total_amount += amount
      { product_id: product.id, quantity: quantity, amount: amount }
    end

    @order = Order.new(products_orders_attributes: products_orders, amount: total_amount)

    result = false

    Order.transaction do
      @order.save!
      update_products_quantity

      result = true
    end

    if result
      cookies['cart'] = { value: nil, path: nil }
      redirect_to order_path(id: @order.token)
    else
      flash[:error] = @order.errors.full_messages
    end
  end

  private
    # ustawia zamówienie po tokenie
    def set_order
      @order = Order.find_by(token: params[:id])
    end

    # pobiera parametry zapytania
    def order_params
      params.require(:products)
    end

    # redukuje liczbę produktów
    def update_products_quantity
      @order.products_orders.each do |po|
        product = po.product
        new_quantity = product.quantity - po.quantity
        product.update!(quantity: new_quantity)
      end
    end
end

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

  <h1>Order  </h1>
<br>
  <h2>Summary  </h2>

<div class="card">
  <div class="card-body">
    <p class="card-text">
      <label>Amount  </label> <%= @order.amount %> <br>
      <label>Order status  </label> <%= @order.status %><br>
      <label>Payment status  </label> <%= @order.payment_status %>
    </p>
    <div class="btn-group" role="group" aria-label="Basic example">
      <%= link_to "Pay", new_payment_path(order_token: @order.token),
            class: "btn btn-primary #{'disabled' if [Payment::COMPLETED_STATUS, Payment::PENDING_STATUS, Payment::WAITING_STATUS, Payment::REQUESTED_STATUS].include?(@order.payment_status)}" %>
      <% if [Payment::PENDING_STATUS, Payment::REQUESTED_STATUS].include?(@order.payment_status) %>
        <%= button_to "Cancel Payment", payments_cancel_path(order_token: @order.token), class: "btn btn-secondary" %>
      <% end %>
    </div>
  </div>
  <div class="card-footer text-muted">
    Your's order token: <var><%= @order.token %></var>. Please save current page to bookmark if you want to track your order status.
  </div>
</div>

<br><br>
  <h2>Detailed  </h2>
<div class="card-columns">
  <% @order.products_orders.each do |product_order| %>
    <div id='cart-product' class="card">
      <img class="card-img-top" style='max-width: 225px' src=<%= product_order.product.picture_url %> alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"><%= product_order.product.name %></h5>
        <p class="card-text"><%= product_order.product.category %></p>
        <label>Ordered items  </label>
        <%= product_order.quantity %> <br>
        <label>Amount  </label>
        <%= product_order.amount %></p>


        <br>
          <%= link_to 'Show', product_order.product, class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>