config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :products, only: %i(show index)
  resources :carts, only: %i(index)
  resources :orders, only: %i(show create)
  resources :payments, only: %i(new create)
  post '/payments/cancel', to: 'payments#cancel'
  post '/payments/provider_notify', to: 'payments#provider_notify'
  root to: 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Aclonica' rel='stylesheet'>

  </head>

  <body>

    <nav class="navbar fixed-top navbar-dark bg-primary">
      <%# TODO add link to last payment and possibility to clear cookies %>
      <%= link_to 'Online Shop', root_path, class: 'navbar-brand' %>
      <ul class="list-inline">
        <div id='cart_min', class='list-inline-item'></div>
        <%= link_to material_icon.shopping_cart.md_36, carts_path, class: 'list-inline-item' %>
        <%= link_to material_icon.remove_shopping_cart.md_36, '#', onclick: "clearCart()", class: 'list-inline-item' %>
      </ul>
    </nav> <br> <br> <br>


    <div class="left-menu">
      <ul class="nav flex-column">
        <li class="nav-item">
          <%= link_to 'All', products_path, class: 'nav-link' %>
        </li>
        <% categories.each do |category|%>
        <li class="nav-item">
          <%= link_to category, products_path(category: category), class: 'nav-link' %>
        </li>

        <%end%>
      </ul>
    </div>
    <div class=""  style='margin-left: 320px'>
        <div style='margin: 20px;'>
    <%= yield %>
    </div>
    </div>
  </div>

    <%= render 'cookies_eu/consent_banner' %>
  </body>
</html>